### ISSUE TITLE
I literally can't even play as myself

### ISSUE THREAD

**Issue by caleblaroche14** [Zavier-Hastings/CWZ-CIS-4520-Project#1]
I went into your game and saw that there wasn't a "Caleb Laroche" character. This needs to be fixed. NOW.

**Comment by cmc04210** [comment]
Thank you for your kind feedback. We value your input. Your issue will be assigned to the next available support agent.

**Comment by Zavier-Hastings** [comment]
Sorry, but the fact that there is no "Caleb Laroche" character is actually a feature of our game. We have explicitly targeted "Caleb Laroche" to leave out of our game because it was determined the game would be more profitable without this character's inclusion. However, we have taken this feedback into consideration and will allow you to name yourself in game, and then you can pretend to be "Caleb Laroche."

**Comment by anaptyxis** [comment]
_sick burn_, bro.

**Comment by wyatthamby** [comment]
It seemed like there probably wasn't much for me to add, but now I'll just write this comment for the sake of writing it. It seems like for cosmetic requests such as this or simple errors such as the lack of a semicolon, it's just a matter of a making quick response and then resuming things as originally intended to do. With larger errors such as consistent structural errors, the degree to which the team should stop doing things and address the issue in the bug report depends on the degree to which it affects user experience.

Yeah, pretty common sense I guess :|
